
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.rice"

[[constraint]]
  branch = "master"
  name = "github.com/deckarep/gosx-notifier"

[[constraint]]
  branch = "master"
  name = "github.com/desertbit/glue"

[[constraint]]
  name = "github.com/dreadl0ck/readline"
  version = "1.4.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.2"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/mvdan/sh"
  version = "2.0.0"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "2.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "0.5.2"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/yaml.v1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
